### ISSUE TITLE
Can't find component when using props

### ISSUE THREAD

**Issue by nicooprat** [vue-email/compiler#10]
Following https://github.com/vue-email/vue-email/issues/64

I'm getting an error `[Vue warn]: Failed to resolve component:` as soon as I use props inside the template, like this:

```vue
<template>
  <Layout title="Title">
    <div>test</div>
  </Layout>
</template>
```

I could create a small reproduction of the issue: https://stackblitz.com/edit/stackblitz-starters-bqsmkk?file=index.ts,templates%2FLayout.vue,templates%2FMain.vue (run `ts-node index` to log the error).

Removing `title="Title"` fixes it.

Any idea why this happens?

Thanks for this package!

Edit: looks like provide/inject works though, so I will rely on this as a temporary workaround

**Comment by Flowko** [comment]
please upgrade to `0.8.6`
