### ISSUE TITLE
CommonJS/ESM error after updating from v0.8.7 to v0.8.8

### ISSUE THREAD

**Issue by chris-si** [vue-email/compiler#16]
Hi,

I just tried to update the compiler package from `v0.8.7` to `v0.8.8` but unfortunately when running my NestJS server I get the following error for the (newly added?) `shikiji` dependency.

```ts
.../node_modules/vue-email/dist/index.cjs:7
const shikiji = require('shikiji');
                ^
Error [ERR_REQUIRE_ESM]: require() of ES Module .../node_modules/vue-email/node_modules/shikiji/dist/index.mjs not supported.
Instead change the require of .../node_modules/vue-email/node_modules/shikiji/dist/index.mjs to a dynamic import() which is available in all CommonJS modules.
```
Seems like that package is unfortunately not fully CommonJS compatible which I think is unfortunately still mandatory for the use with NestJS.

I just downgraded to `v0.8.7` again which works fine again as a 'workaround' for now. But it would be nice if future version could still support CommonJS as NestJS unfortunately hasn't upgraded to ESM yet.

**Comment by Flowko** [comment]
would you be down for a simple reproduction, just to have a general idea if we can resolve this or not

**Comment by phat-dang** [comment]
I have another project still working with @vue-email/compiler v0.8.5, so I tried to downgrade the @vue-email/compiler version of the current project but still got the error.

old project package.json - @vue-email/compiler v0.8.5  - it's working

```
"dependencies": {
    "@nestjs/common": "^10.3.0",
    "@nestjs/config": "^3.1.1",
    "@nestjs/core": "^10.3.0",
    "@nestjs/mapped-types": "*",
    "@nestjs/platform-express": "^10.3.0",
    "@vue-email/compiler": "^0.8.5",
    "class-transformer": "^0.5.1",
    "class-validator": "^0.14.0",
    "nodemailer": "^6.9.7",
    "reflect-metadata": "^0.1.13",
    "rxjs": "^7.8.1"
  },
  "devDependencies": {
    "@nestjs/cli": "^10.2.1",
    "@nestjs/schematics": "^10.0.3",
    "@nestjs/testing": "^10.3.0",
    "@types/express": "^4.17.21",
    "@types/jest": "^29.5.11",
    "@types/node": "^20.10.5",
    "@types/nodemailer": "^6.4.14",
    "@types/supertest": "^6.0.1",
    "@typescript-eslint/eslint-plugin": "^6.16.0",
    "@typescript-eslint/parser": "^6.16.0",
    "eslint": "^8.56.0",
    "eslint-config-prettier": "^9.1.0",
    "eslint-plugin-prettier": "^5.1.2",
    "jest": "^29.7.0",
    "prettier": "^3.1.1",
    "source-map-support": "^0.5.21",
    "supertest": "^6.3.3",
    "ts-jest": "^29.1.1",
    "ts-loader": "^9.5.1",
    "ts-node": "^10.9.2",
    "tsconfig-paths": "^4.2.0",
    "typescript": "^5.3.3"
  },
```

Current project, got error

```
"dependencies": {
    "@nestjs/cache-manager": "^2.2.1",
    "@nestjs/common": "^10.3.2",
    "@nestjs/config": "^3.2.0",
    "@nestjs/core": "^10.3.2",
    "@nestjs/mapped-types": "^2.0.5",
    "@nestjs/mongoose": "^10.0.4",
    "@nestjs/platform-express": "^10.3.2",
    "@vue-email/compiler": "^0.8.10",
    "cache-manager": "^5.4.0",
    "class-transformer": "^0.5.1",
    "class-validator": "^0.14.1",
    "mongoose": "^8.1.1",
    "nodemailer": "^6.9.9",
    "reflect-metadata": "^0.1.13",
    "rxjs": "^7.8.1"
  },
  "devDependencies": {
    "@nestjs/cli": "^10.3.2",
    "@nestjs/schematics": "^10.1.1",
    "@nestjs/testing": "^10.3.2",
    "@types/express": "^4.17.21",
    "@types/jest": "^29.5.12",
    "@types/multer": "^1.4.11",
    "@types/node": "^20.11.16",
    "@types/nodemailer": "^6.4.14",
    "@types/supertest": "^6.0.2",
    "@typescript-eslint/eslint-plugin": "^6.21.0",
    "@typescript-eslint/parser": "^6.21.0",
    "eslint": "^8.56.0",
    "eslint-config-prettier": "^9.1.0",
    "eslint-plugin-prettier": "^5.1.3",
    "jest": "^29.7.0",
    "prettier": "^3.2.5",
    "source-map-support": "^0.5.21",
    "supertest": "^6.3.4",
    "ts-jest": "^29.1.2",
    "ts-loader": "^9.5.1",
    "ts-node": "^10.9.2",
    "tsconfig-paths": "^4.2.0",
    "typescript": "^5.3.3"
  }
```

**Comment by chris-si** [comment]
[Here](https://stackblitz.com/edit/stackblitz-starters-vwave6?file=src%2Fapp.controller.ts) is a simple reproduction on StackBlitz.

It just uses a new NestJS project with vue-email as additional dependency. For simplicity everything important is implemented in `app.controller.ts` and the relevant code is called right on startup which also leads to the `shikiji` error.

**Comment by chris-si** [comment]
Just tested it and it works fine for the basic example I tested. Thanks for the fix!

**Comment by Flowko** [comment]
will release it, you can update the version to `0.8.11`

**Comment by chris-si** [comment]
Just as an FYI since I just came across it: It seems with the release of shiki 1.0.0, [shikiji is now shiki again](https://github.com/shikijs/shiki/releases/tag/v1.0.0).

**Comment by Flowko** [comment]
yeah, i did update to the latest version of shiki, not sure if that will resolve anything, but please do check

**Comment by phat-dang** [comment]
`0.8.11` it worked for me! Thanks for the fix

**Comment by chris-si** [comment]
> not sure if that will resolve anything [...]

No, unfortunately it won't, since it's now also pure ESM

**Comment by phat-dang** [comment]
@Flowko I got this issue again with the new update **0.8.12**

**Comment by chris-si** [comment]
It looks like the `vue-email` dependency just got bumped down from the edge release back to the latest release `0.8.8` again which doesn't include the fix yet.

**Comment by Flowko** [comment]
ah, somhow i forgot to release those changes, doing it now @phat-dang @chris-si

**Comment by Flowko** [comment]
please try the latest versions, should be there now, thanks for letting me know!
