### ISSUE TITLE
[Question] How to render email as text with ssr ?

### ISSUE THREAD

**Issue by geminigeek** [vue-email/compiler#3]
hi,
this is in reference to this page https://www.vuemail.net/getting-started/ssr , the page shows how to render an email to html, how can we render it as plain text. i tried like this but i am still getting html?

```
const emailText = await vueEmail.render(
  emailTemplate,
  {
    props: data,
  },
  {
    plainText: true,
  },
)
```

**Comment by Flowko** [comment]
its not available at `0.8.2`, no need to pass any option, the render function should return both `html` and `text` in one object
