### ISSUE TITLE
Compiler doesn't find Component when using inline closing

### ISSUE THREAD

**Issue by Niki2k1** [vue-email/compiler#9]
When using a Component like this: `<Header />` it can't be imported.

I believe it is because of the Regex for finding Components:
https://github.com/vue-email/compiler/blob/7c4a09ffaaf811ac748b70c987b5fcccb83d99a0/src/template.ts#L113-L115

A Regex Pattern like this might fix the issue: https://regex101.com/r/XUPZyE/1

**Comment by Flowko** [comment]
hi, thanks for the link, but sadly that will break in some cases, i reverted that change for now, till i find a better way to handle those cases, if u can upgrade to `0.8.6`
